FROM node:18.17.0-alpine as prod

RUN npm i -g npm@10.3.0

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./

RUN npm i --only=production

RUN rm -f package.json